apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-hello
  name: node-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-hello
    spec:
      containers:
      - image: us.icr.io/samples/node-hello-world:v1
        name: node-hello
        resources: {}
status: {}
